workflows:
  ios-init:
    name: Init iOS Project on macOS
    environment:
      groups:
        - github_access
      flutter: stable
      xcode: latest
      vars:
        GIT_BRANCH: "main" # ou "master" selon ton cas

    scripts:
      - name: Configure Git
        script: |
          git config --global user.name "Codemagic Bot"
          git config --global user.email "codemagic@bot.com"
          git remote set-url origin https://oauth2:${GITHUB_TOKEN}@github.com/Mykie58/flutter_ios_template.git

      - name: Remove existing ios folder (if any)
        script: |
          git rm -rf ios || echo "No ios dir tracked"
          rm -rf ios

      - name: Generate iOS folder
        script: |
          flutter create .

      - name: Commit and push ios/
        script: |
          git add ios/
          git commit -m "Regenerate ios folder via CI" || git commit --allow-empty -m "Force update to trigger push"
          git push origin $GIT_BRANCH --verbose

