workflows:
  ios-init:
    name: iOS Init (recreate ios folder)
    environment:
      flutter: stable
      xcode: latest
      vars:
        GIT_BRANCH: "ios-init"
      groups:
        - github_access  # <- Ce groupe doit contenir GITHUB_TOKEN
    scripts:
      - name: Clean existing ios/ folder
        script: rm -rf ios
      - name: Recreate Flutter iOS folder
        script: flutter create .
      - name: Commit new ios folder to Git
        script: |
          git config user.email "builder@codemagic.io"
          git config user.name "Codemagic Bot"
          git checkout -b $GIT_BRANCH || git checkout $GIT_BRANCH
          git add ios
          git commit -m "Recreate ios folder via Codemagic" || echo "Nothing to commit"
          git push -u origin $GIT_BRANCH



