workflows:
  ios-simulator:
    name: Build iOS simulator version
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS for simulator
        script: flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/**/*
